### ISSUE TITLE
Runtime error with controlnet

### ISSUE THREAD

**Issue by Z0rx** [muerrilla/stable-diffusion-NPW#4] opened 2023-05-21 00:42 UTC
Hey,

Today i updated controlnet and NPM , so ill started to use controlnet. If you set NPM above 1.00 wight the script drops an error.

"   File "C:\Users\datenschutzduhrnsn\Desktop\ai\stable-diffusion-webui\extensions\stable-diffusion-NPW\scripts\npw.py", line 90, in denoiser_callback
    new_uncond = torch.lerp(empty_uncond_concat, uncond, self.weight)
RuntimeError: The size of tensor a (1463) must match the size of tensor b (1464) at non-singleton dimension 1 "

**Comment by muerrilla** [comment] 2023-05-22 14:27
I couldn't replicate that. Could you provide more context? My prompt and negative prompt are ~150 tokens long, and I'm using: 
python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.23.0  •  commit: 22bcc7be  •  controlnet: v1.1.173

**Comment by Skifoid** [comment] 2023-05-22 14:35
I think this is caused by a fresh version of controlnet (the error appeared near the version ControlNet v1.1.180+). The problems started after the controlnet update, as it seemed to me.

**Comment by D0rkerz** [comment] 2023-05-22 14:47
> I couldn't replicate that. Could you provide more context? My prompt and negative prompt are ~150 tokens long, and I'm using: python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.23.0  •  A1111 commit: 22bcc7be  •  controlnet: v1.1.173  •  NPW commit: [72a9348](https://github.com/muerrilla/stable-diffusion-NPW/commit/72a934827f4684c5df831ecb39ab8729e9edc0f5)

Update Controlnet :)

**Comment by muerrilla** [comment] 2023-05-22 22:24
Should be fixed. At least it works! 
Please update and test to see if it works **as expected**, and let me know if I should close the issue.

**Comment by Skifoid** [comment] 2023-05-23 07:35
Seems to be no problem now. Thank you.

**Comment by Z0rx** [comment] 2023-05-24 07:24
Fixed thanks!

**Closed** 2023-05-24 07:24 UTC
